elasticsearchHost: localhost:9300
clusterName: performance
usernamePassword: jettro:nopiforme

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001